# --- Input Files ---
mesh_path: temp/mesh/mesh.ply              # Accepts .obj, .ply, .stl
cameras_path: temp/cameras.sfm             # Camera info file path
camera_format: meshroom                    # Format ('agisoft' or 'meshroom')
images_path: temp/images                   # Images folder path
extensions: [ png, jpg, jpeg ]             # Image formats found in the images folder

# --- Output ---
output_folder: temp/output/                # Where depth maps/renders will be saved
save_scene: false                          # Set to true to save RGB renders (slower processing, memory intensive)

# --- Options ---
distortion:
  enabled: false                           # Apply distortion to the depth maps so they match the original images captured
  max_iterations: 100                      # Maximum number of iterations before terminating
  tolerance: 0.001                         # Relative tolerance for convergence
  damping: 1.0                             # Damping factor when calculating distortion mappings. Helps prevent
                                           # overflows but will increase computational time

perspective_correction:
  enabled: false                           # Calculate homography to align the depth maps with the original image
  model: similarity                        # The model type ('euclidean', 'similarity', 'affine', or 'projective')
  minimum_match_count: 4                   # Minimum matches needed for homography
  distance_ratio: 0.70                     # Ratio used for Lowe's ratio test when matching points.
  ransac_threshold: 5.0                    # RANSAC threshold for homography outliers
  max_iterations: 10000                    # Maximum number of iterations for RANSAC
  padding: 1000                            # The amount of padding (in pixels) around the borders.
                                           # Will be cropped to adjust for warping by homography

scale_mesh:
  enabled: false                           # Rescale the mesh given known poses
  pose_1: filename_for_pose_1              # The id of the first pose along the mesh
  pose_2: filename_for_pose_2              # The id of the second pose along the mesh
  distance: 1.0                            # The true distance between the two poses in meters

manual_view:
  enabled: false                           # Set a manual view for the ray-tracing. Disables per-camera rendering.
  use_center: true                         # Place the reference frame at the center of the mesh. Otherwise, use the mesh's reference frame.
  position: [0, 0, 0]                      # A translation vector ([x, y, z]).
  orientation: [1, 0, 0, 0]                # A quaternion array ([w, x, y, z]).
  height: 3024                             # The resolution width of the image (pixels)
  width: 4032                              # The resolution height of the image (pixels)
  fx: 3277                                 # The focal length of the simulated camera in the x-axis (pixels)
  fy: 3277                                 # The focal length of the simulated camera in the y-axis (pixels)
